name: musica-env
channels:
  - defaults
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - scipy
  - tqdm
  - pre-commit
  - ipykernel
  - pip:
      - wandb
      - torch
      - torchvision
      - torchaudio
      - mido
      - librosa
      - pretty_midi
      - miditok
